export const REFERENCE_PERMISSIONS = [
  'show pos dashboard',
  'show crm dashboard',
  'show hrm dashboard',
  'show project dashboard',
  'show account dashboard',
  'manage user',
  'create user',
  'edit user',
  'delete user',
  'create language',
  'manage role',
  'create role',
  'edit role',
  'delete role',
  'manage permission',
  'create permission',
  'edit permission',
  'delete permission',
  'manage company settings',
  'manage print settings',
  'manage business settings',
  'manage stripe settings',
  'manage expense',
  'create expense',
  'edit expense',
  'delete expense',
  'manage invoice',
  'create invoice',
  'edit invoice',
  'delete invoice',
  'show invoice',
  'create payment invoice',
  'delete payment invoice',
  'send invoice',
  'delete invoice product',
  'convert invoice',
  'manage constant unit',
  'create constant unit',
  'edit constant unit',
  'delete constant unit',
  'manage constant tax',
  'create constant tax',
  'edit constant tax',
  'delete constant tax',
  'manage constant category',
  'create constant category',
  'edit constant category',
  'delete constant category',
  'manage product & service',
  'create product & service',
  'edit product & service',
  'delete product & service',
  'manage customer',
  'create customer',
  'edit customer',
  'delete customer',
  'show customer',
  'manage vender',
  'create vender',
  'edit vender',
  'delete vender',
  'show vender',
  'manage bank account',
  'create bank account',
  'edit bank account',
  'delete bank account',
  'manage bank transfer',
  'create bank transfer',
  'edit bank transfer',
  'delete bank transfer',
  'manage transaction',
  'manage revenue',
  'create revenue',
  'edit revenue',
  'delete revenue',
  'manage bill',
  'create bill',
  'edit bill',
  'delete bill',
  'show bill',
  'manage payment',
  'create payment',
  'edit payment',
  'delete payment',
  'delete bill product',
  'send bill',
  'create payment bill',
  'delete payment bill',
  'manage order',
  'manage customer payment',
  'manage customer transaction',
  'manage customer invoice',
  'manage vender bill',
  'manage vender payment',
  'manage vender transaction',
  'manage credit note',
  'create credit note',
  'edit credit note',
  'delete credit note',
  'manage debit note',
  'create debit note',
  'edit debit note',
  'delete debit note',
  'duplicate invoice',
  'duplicate bill',
  'manage proposal',
  'create proposal',
  'edit proposal',
  'delete proposal',
  'duplicate proposal',
  'show proposal',
  'send proposal',
  'delete proposal product',
  'manage customer proposal',
  'manage goal',
  'create goal',
  'edit goal',
  'delete goal',
  'manage assets',
  'create assets',
  'edit assets',
  'delete assets',
  'manage constant custom field',
  'create constant custom field',
  'edit constant custom field',
  'delete constant custom field',
  'manage chart of account',
  'create chart of account',
  'edit chart of account',
  'delete chart of account',
  'manage journal entry',
  'create journal entry',
  'edit journal entry',
  'delete journal entry',
  'show journal entry',
  'manage client',
  'create client',
  'edit client',
  'delete client',
  'manage lead',
  'create lead',
  'view lead',
  'edit lead',
  'delete lead',
  'move lead',
  'create lead call',
  'edit lead call',
  'delete lead call',
  'create lead email',
  'manage pipeline',
  'create pipeline',
  'edit pipeline',
  'delete pipeline',
  'manage lead stage',
  'create lead stage',
  'edit lead stage',
  'delete lead stage',
  'convert lead to deal',
  'manage source',
  'create source',
  'edit source',
  'delete source',
  'manage label',
  'create label',
  'edit label',
  'delete label',
  'manage deal',
  'create deal',
  'view task',
  'create task',
  'edit task',
  'delete task',
  'edit deal',
  'view deal',
  'delete deal',
  'move deal',
  'create deal call',
  'edit deal call',
  'delete deal call',
  'create deal email',
  'manage stage',
  'create stage',
  'edit stage',
  'delete stage',
  'manage employee',
  'create employee',
  'view employee',
  'edit employee',
  'delete employee',
  'manage employee profile',
  'show employee profile',
  'manage department',
  'create department',
  'view department',
  'edit department',
  'delete department',
  'manage designation',
  'create designation',
  'view designation',
  'edit designation',
  'delete designation',
  'manage branch',
  'create branch',
  'edit branch',
  'delete branch',
  'manage document type',
  'create document type',
  'edit document type',
  'delete document type',
  'manage document',
  'create document',
  'edit document',
  'delete document',
  'manage payslip type',
  'create payslip type',
  'edit payslip type',
  'delete payslip type',
  'create allowance',
  'edit allowance',
  'delete allowance',
  'create commission',
  'edit commission',
  'delete commission',
  'manage allowance option',
  'create allowance option',
  'edit allowance option',
  'delete allowance option',
  'manage loan option',
  'create loan option',
  'edit loan option',
  'delete loan option',
  'manage deduction option',
  'create deduction option',
  'edit deduction option',
  'delete deduction option',
  'create loan',
  'edit loan',
  'delete loan',
  'create saturation deduction',
  'edit saturation deduction',
  'delete saturation deduction',
  'create other payment',
  'edit other payment',
  'delete other payment',
  'create overtime',
  'edit overtime',
  'delete overtime',
  'manage set salary',
  'edit set salary',
  'manage pay slip',
  'create set salary',
  'create pay slip',
  'manage company policy',
  'create company policy',
  'edit company policy',
  'manage appraisal',
  'create appraisal',
  'edit appraisal',
  'show appraisal',
  'delete appraisal',
  'manage goal tracking',
  'create goal tracking',
  'edit goal tracking',
  'delete goal tracking',
  'manage goal type',
  'create goal type',
  'edit goal type',
  'delete goal type',
  'manage indicator',
  'create indicator',
  'edit indicator',
  'show indicator',
  'delete indicator',
  'manage training',
  'create training',
  'edit training',
  'delete training',
  'show training',
  'manage trainer',
  'create trainer',
  'edit trainer',
  'delete trainer',
  'manage training type',
  'create training type',
  'edit training type',
  'delete training type',
  'manage award',
  'create award',
  'edit award',
  'delete award',
  'manage award type',
  'create award type',
  'edit award type',
  'delete award type',
  'manage resignation',
  'create resignation',
  'edit resignation',
  'delete resignation',
  'manage travel',
  'create travel',
  'edit travel',
  'delete travel',
  'manage promotion',
  'create promotion',
  'edit promotion',
  'delete promotion',
  'manage complaint',
  'create complaint',
  'edit complaint',
  'delete complaint',
  'manage warning',
  'create warning',
  'edit warning',
  'delete warning',
  'manage termination',
  'create termination',
  'edit termination',
  'delete termination',
  'manage termination type',
  'create termination type',
  'edit termination type',
  'delete termination type',
  'manage job application',
  'create job application',
  'show job application',
  'delete job application',
  'move job application',
  'add job application skill',
  'add job application note',
  'delete job application note',
  'manage job onBoard',
  'manage job category',
  'create job category',
  'edit job category',
  'delete job category',
  'manage job',
  'create job',
  'edit job',
  'show job',
  'delete job',
  'manage job stage',
  'create job stage',
  'edit job stage',
  'delete job stage',
  'Manage Competencies',
  'Create Competencies',
  'Edit Competencies',
  'Delete Competencies',
  'manage custom question',
  'create custom question',
  'edit custom question',
  'delete custom question',
  'create interview schedule',
  'edit interview schedule',
  'delete interview schedule',
  'show interview schedule',
  'create estimation',
  'view estimation',
  'edit estimation',
  'delete estimation',
  'edit holiday',
  'create holiday',
  'delete holiday',
  'manage holiday',
  'show career',
  'manage meeting',
  'create meeting',
  'edit meeting',
  'delete meeting',
  'manage event',
  'create event',
  'edit event',
  'delete event',
  'manage transfer',
  'create transfer',
  'edit transfer',
  'delete transfer',
  'manage announcement',
  'create announcement',
  'edit announcement',
  'delete announcement',
  'manage leave',
  'create leave',
  'edit leave',
  'delete leave',
  'manage leave type',
  'create leave type',
  'edit leave type',
  'delete leave type',
  'manage attendance',
  'create attendance',
  'edit attendance',
  'delete attendance',
  'manage report',
  'manage project',
  'create project',
  'view project',
  'edit project',
  'delete project',
  'create milestone',
  'edit milestone',
  'delete milestone',
  'view milestone',
  'view grant chart',
  'manage project stage',
  'create project stage',
  'edit project stage',
  'delete project stage',
  'view timesheet',
  'view expense',
  'manage project task',
  'create project task',
  'edit project task',
  'view project task',
  'delete project task',
  'view activity',
  'view CRM activity',
  'manage project task stage',
  'edit project task stage',
  'create project task stage',
  'delete project task stage',
  'manage timesheet',
  'create timesheet',
  'edit timesheet',
  'delete timesheet',
  'manage bug report',
  'create bug report',
  'edit bug report',
  'delete bug report',
  'move bug report',
  'manage bug status',
  'create bug status',
  'edit bug status',
  'delete bug status',
  'manage client dashboard',
  'manage super admin dashboard',
  'manage system settings',
  'manage plan',
  'create plan',
  'edit plan',
  'manage coupon',
  'create coupon',
  'edit coupon',
  'delete coupon',
  'manage company plan',
  'manage form builder',
  'create form builder',
  'edit form builder',
  'delete form builder',
  'manage performance type',
  'create performance type',
  'edit performance type',
  'delete performance type',
  'manage form field',
  'create form field',
  'edit form field',
  'delete form field',
  'view form response',
  'create budget plan',
  'edit budget plan',
  'manage budget plan',
  'delete budget plan',
  'view budget plan',
  'manage warehouse',
  'create warehouse',
  'edit warehouse',
  'show warehouse',
  'delete warehouse',
  'manage purchase',
  'create purchase',
  'edit purchase',
  'show purchase',
  'delete purchase',
  'send purchase',
  'create payment purchase',
  'delete payment purchase',
  'manage pos',
  'manage contract type',
  'create contract type',
  'edit contract type',
  'delete contract type',
  'manage contract',
  'create contract',
  'edit contract',
  'delete contract',
  'show contract',
  'create barcode',
  'create webhook',
  'edit webhook',
  'delete webhook',
  'manage project expense',
  'create project expense',
  'edit project expense',
  'delete project expense',
  'manage quotation',
  'create quotation',
  'edit quotation',
  'delete quotation',
  'show quotation',
  'convert quotation',
  'show pos',
  'manage zoom meeting',
  'create zoom meeting',
  'show zoom meeting',
  'delete zoom meeting',
  'delete company policy',
  'manage biometric attendance',
  'biometric attendance synchronize',
] as const
