export async function seedContracts(prisma: any) {
  const db = prisma as any
  console.log("Seeding contracts...")

  const contracts = [
    {
      contractId: "CTR-2025-001",
      clientName: "PT Maju Jaya",
      subject: "Implementasi ERP PT Maju Jaya",
      value: 350000000,
      type: "Implementation",
      startDate: new Date("2025-11-01"),
      endDate: new Date("2026-01-31"),
      description: "Kontrak implementasi ERP full module selama 3 bulan.",
      status: "accept",
      contractDescription: "Kontrak implementasi ERP untuk PT Maju Jaya.",
    },
    {
      contractId: "CTR-2025-002",
      clientName: "CV Kreatif Digital",
      subject: "Maintenance CRM CV Kreatif Digital",
      value: 120000000,
      type: "Support",
      startDate: new Date("2025-11-10"),
      endDate: new Date("2026-11-09"),
      description: "Maintenance dan support tahunan untuk modul CRM.",
      status: "accept",
      contractDescription: "Kontrak maintenance CRM tahunan.",
    },
    {
      contractId: "CTR-2025-003",
      clientName: "PT Teknologi",
      subject: "Development Mobile App PT Teknologi",
      value: 500000000,
      type: "Development",
      startDate: new Date("2025-12-01"),
      endDate: new Date("2026-06-30"),
      description: "Pengembangan aplikasi mobile untuk platform iOS dan Android.",
      status: "accept",
      contractDescription: "Kontrak pengembangan aplikasi mobile.",
    },
    {
      contractId: "CTR-2025-004",
      clientName: "PT Digital Solutions",
      subject: "Cloud Migration Services",
      value: 250000000,
      type: "Migration",
      startDate: new Date("2025-10-15"),
      endDate: new Date("2026-04-14"),
      description: "Migrasi infrastruktur ke cloud dan optimasi.",
      status: "pending",
      contractDescription: "Kontrak layanan migrasi cloud.",
    },
    {
      contractId: "CTR-2025-005",
      clientName: "PT Keamanan Data",
      subject: "Security Audit & Compliance",
      value: 180000000,
      type: "Audit",
      startDate: new Date("2025-09-01"),
      endDate: new Date("2025-12-31"),
      description: "Audit keamanan dan compliance standar industri.",
      status: "accept",
      contractDescription: "Kontrak audit keamanan dan compliance.",
    },
    {
      contractId: "CTR-2025-006",
      clientName: "CV Optimasi Sistem",
      subject: "Database Optimization",
      value: 95000000,
      type: "Optimization",
      startDate: new Date("2025-11-20"),
      endDate: new Date("2026-02-19"),
      description: "Optimasi database dan tuning performa.",
      status: "accept",
      contractDescription: "Kontrak optimasi database.",
    },
    {
      contractId: "CTR-2025-007",
      clientName: "PT Retail Online",
      subject: "E-Commerce Platform Development",
      value: 750000000,
      type: "Development",
      startDate: new Date("2026-01-01"),
      endDate: new Date("2026-12-31"),
      description: "Pengembangan platform e-commerce lengkap.",
      status: "pending",
      contractDescription: "Kontrak pengembangan platform e-commerce.",
    },
    {
      contractId: "CTR-2025-008",
      clientName: "PT Infrastruktur",
      subject: "IT Infrastructure Setup",
      value: 420000000,
      type: "Infrastructure",
      startDate: new Date("2025-10-01"),
      endDate: new Date("2026-03-31"),
      description: "Setup infrastruktur IT dan jaringan.",
      status: "accept",
      contractDescription: "Kontrak setup infrastruktur IT.",
    },
    {
      contractId: "CTR-2025-009",
      clientName: "PT Pelatihan",
      subject: "Training & Consultation",
      value: 75000000,
      type: "Training",
      startDate: new Date("2025-11-15"),
      endDate: new Date("2026-01-14"),
      description: "Pelatihan dan konsultasi teknis.",
      status: "accept",
      contractDescription: "Kontrak training dan konsultasi.",
    },
    {
      contractId: "CTR-2025-010",
      clientName: "PT Integrasi Sistem",
      subject: "System Integration Services",
      value: 320000000,
      type: "Integration",
      startDate: new Date("2026-02-01"),
      endDate: new Date("2026-08-31"),
      description: "Integrasi sistem dan API dengan pihak ketiga.",
      status: "pending",
      contractDescription: "Kontrak layanan integrasi sistem.",
    },
  ]

  for (const contract of contracts) {
    await db.contract.upsert({
      where: { contractId: contract.contractId },
      update: {},
      create: contract,
    })
  }

  console.log(`Seeded ${contracts.length} contracts.`)
}

