export async function seedVendors(prisma: any) {
  console.log("Seeding vendors...");

  const user = await prisma.user.findFirst({
    where: {
      role: {
        in: ["super admin", "company"],
      },
      branchId: {
        not: null,
      },
    },
  });

  if (!user) {
    console.log(
      "Warning: Super Admin or Company user with branchId not found. Seeding vendors with first available branch and createdById = null.",
    );
  }

  const branchId =
    user?.branchId || (await prisma.branch.findFirst({ orderBy: { createdAt: "asc" } }))?.id;

  if (!branchId) {
    console.log("Skipping vendor seed: Branch not found.");
    return;
  }

  const vendors = [
    {
      vendorCode: "VDR-001",
      name: "PT Supply Berkah",
      email: "vendor@supplyberkah.id",
      contact: "+62 21 5555 8888",
      taxNumber: "01.234.567.8-999.000",
      balance: 150000000,
      billingName: "PT Supply Berkah",
      billingPhone: "+62 21 5555 8888",
      billingAddress: "Jl. Industri No. 10",
      billingCity: "Jakarta",
      billingState: "DKI Jakarta",
      billingCountry: "Indonesia",
      billingZip: "13110",
      shippingName: "Gudang Supply Berkah",
      shippingPhone: "+62 21 5555 8888",
      shippingAddress: "Kawasan Pergudangan Berkah Blok A1",
      shippingCity: "Bekasi",
      shippingState: "Jawa Barat",
      shippingCountry: "Indonesia",
      shippingZip: "17145",
      branchId,
      createdById: user?.id ?? null,
    },
    {
      vendorCode: "VDR-002",
      name: "CV Logistik Nusantara",
      email: "info@logistiknusantara.co.id",
      contact: "+62 31 7777 8888",
      taxNumber: "02.111.222.3-444.000",
      balance: 85000000,
      billingName: "CV Logistik Nusantara",
      billingPhone: "+62 31 7777 8888",
      billingAddress: "Jl. Tanjung Perak No. 7",
      billingCity: "Surabaya",
      billingState: "Jawa Timur",
      billingCountry: "Indonesia",
      billingZip: "60165",
      shippingName: "Gudang Logistik Nusantara",
      shippingPhone: "+62 31 7777 8888",
      shippingAddress: "Kawasan Industri Pelabuhan Blok B2",
      shippingCity: "Surabaya",
      shippingState: "Jawa Timur",
      shippingCountry: "Indonesia",
      shippingZip: "60166",
      branchId,
      createdById: user?.id ?? null,
    },
    {
      vendorCode: "VDR-003",
      name: "OfficeMart",
      email: "contact@officemart.id",
      contact: "+62 21 8888 7777",
      taxNumber: "03.333.444.5-666.000",
      balance: 25000000,
      billingName: "OfficeMart Indonesia",
      billingPhone: "+62 21 8888 7777",
      billingAddress: "Jl. Kantor Raya No. 12",
      billingCity: "Jakarta",
      billingState: "DKI Jakarta",
      billingCountry: "Indonesia",
      billingZip: "10110",
      shippingName: "Gudang OfficeMart",
      shippingPhone: "+62 21 8888 7777",
      shippingAddress: "Kawasan Pergudangan DKI Blok C3",
      shippingCity: "Jakarta",
      shippingState: "DKI Jakarta",
      shippingCountry: "Indonesia",
      shippingZip: "13110",
      branchId,
      createdById: user?.id ?? null,
    },
    {
      vendorCode: "VDR-004",
      name: "BlueBird Taxi",
      email: "support@bluebird.co.id",
      contact: "+62 21 7777 6666",
      taxNumber: "04.555.666.7-888.000",
      balance: 5000000,
      billingName: "PT Blue Bird Tbk",
      billingPhone: "+62 21 7777 6666",
      billingAddress: "Jl. Mampang Prapatan Raya No. 60",
      billingCity: "Jakarta",
      billingState: "DKI Jakarta",
      billingCountry: "Indonesia",
      billingZip: "12790",
      shippingName: "BlueBird Pool",
      shippingPhone: "+62 21 7777 6666",
      shippingAddress: "Jl. Raya Pool No. 3",
      shippingCity: "Jakarta",
      shippingState: "DKI Jakarta",
      shippingCountry: "Indonesia",
      shippingZip: "12790",
      branchId,
      createdById: user?.id ?? null,
    },
    {
      vendorCode: "VDR-005",
      name: "Coffee House",
      email: "hello@coffeehouse.id",
      contact: "+62 22 555 2222",
      taxNumber: "05.222.333.4-555.000",
      balance: 1500000,
      billingName: "Coffee House",
      billingPhone: "+62 22 555 2222",
      billingAddress: "Jl. Braga No. 5",
      billingCity: "Bandung",
      billingState: "Jawa Barat",
      billingCountry: "Indonesia",
      billingZip: "40111",
      shippingName: "Coffee House Kitchen",
      shippingPhone: "+62 22 555 2222",
      shippingAddress: "Jl. Braga No. 5",
      shippingCity: "Bandung",
      shippingState: "Jawa Barat",
      shippingCountry: "Indonesia",
      shippingZip: "40111",
      branchId,
      createdById: user?.id ?? null,
    },
    {
      vendorCode: "VDR-006",
      name: "Coworking Space",
      email: "billing@coworkhub.id",
      contact: "+62 21 3333 2222",
      taxNumber: "06.111.222.3-444.000",
      balance: 3000000,
      billingName: "CoworkHub Indonesia",
      billingPhone: "+62 21 3333 2222",
      billingAddress: "Jl. Sudirman No. 123",
      billingCity: "Jakarta",
      billingState: "DKI Jakarta",
      billingCountry: "Indonesia",
      billingZip: "10270",
      shippingName: "CoworkHub Jakarta",
      shippingPhone: "+62 21 3333 2222",
      shippingAddress: "Jl. Sudirman No. 123",
      shippingCity: "Jakarta",
      shippingState: "DKI Jakarta",
      shippingCountry: "Indonesia",
      shippingZip: "10270",
      branchId,
      createdById: user?.id ?? null,
    },
    {
      vendorCode: "VDR-007",
      name: "State Electricity Company",
      email: "pln@pln.co.id",
      contact: "+62 21 123",
      taxNumber: "07.777.888.9-000.000",
      balance: 10000000,
      billingName: "PT PLN (Persero)",
      billingPhone: "+62 21 123",
      billingAddress: "Jl. Trunojoyo Blok M-I No. 135",
      billingCity: "Jakarta",
      billingState: "DKI Jakarta",
      billingCountry: "Indonesia",
      billingZip: "12160",
      shippingName: "PLN Distribution",
      shippingPhone: "+62 21 123",
      shippingAddress: "Jl. Trunojoyo Blok M-I No. 135",
      shippingCity: "Jakarta",
      shippingState: "DKI Jakarta",
      shippingCountry: "Indonesia",
      shippingZip: "12160",
      branchId,
      createdById: user?.id ?? null,
    },
  ];

  for (const vendorData of vendors) {
    await prisma.vendor.upsert({
      where: { vendorCode: vendorData.vendorCode },
      update: {},
      create: vendorData,
    });
  }

  console.log(`Seeded ${vendors.length} vendors.`);
}

